### PR TITLE
Adding zeek script to read MacOS process events

### PR DESCRIPTION
**Pull request by Wajihulhassan**
I have created a Zeek script to fetch MacOS process events from Zeek-Agent's table. I also corrected a typo in README.

### CODE REVIEW

**Comment by rsmmr** [comment]
Cool!

I imagine there's an agent-side PR going to come to go along with this, let's wait for that before reviewing/merging.

**Comment by rsmmr** [comment]
Actually, maybe not. Let me turn this into a question: Did you make any agent-side changes or does this script work as is?

**Comment by Wajihulhassan** [comment]
This script works as is because the process events table -- which this script queries -- was already there in Zeek-agent.

**Review by bbannier — APPROVED** [review]
LGTM. With modest development activity this table produces logs at about 1Mb/s for my machine which is substantial, but I guess expected and in a way exactly the point.

**Pull request merged**
